document.addEventListener('alpine:init', () => {
    Alpine.data('mission', () => ({
        missions: [],
        // Missions contains Slots
        // Slot: Type, Instruction, Name
        // Missions also contain mission instructions
        // Persona, Voice, Background, Callback URL
        // Slot Instructions shall be generated by LLM/Ai, with the Instructions for this mission
        // Mission will be posted to Dialogflow and generate a small Flow that gathers informations to fill Slots

    }));
});

function missionForm() {
    return {
      mission: {
        persona: '',
        tonfall: 0.5,
        background: '',
        backendUrl: '',
        slots: []
      },
      addSlot() {
        this.mission.slots.push({ name: '', type: 'string', instruction: '' });
      },
      removeSlot(index) {
        this.mission.slots.splice(index, 1);
      }
    }
  }